import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CustomerNavbar } from "@/components/Home/HomeNavbar";
 
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "@/Provider/Providers";
import { Header } from "@/components/Home/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
    
     
     <AuthProvider>
      {/* <Header/> */}
        {children}
             <Toaster/>
     </AuthProvider>
        
        </body>
    </html>
  );
}
