import type { Metadata } from "next";

import "./globals.css";
 
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "@/Provider/Providers";
 



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
    
     
     <AuthProvider>
 
        {children}
             <Toaster/>
     </AuthProvider>
        
        </body>
    </html>
  );
}
